/**
 * Model Registry - Defines all available models with their capabilities,
 * strengths, pricing, and metadata used by the routing algorithm.
 */

export const PROVIDERS = {
    openai: { name: 'OpenAI', color: '#10a37f', icon: 'O' },
    anthropic: { name: 'Anthropic', color: '#d97706', icon: 'A' },
    google: { name: 'Google', color: '#4285f4', icon: 'G' },
    meta: { name: 'Meta', color: '#0668E1', icon: 'M' },
    mistral: { name: 'Mistral', color: '#f97316', icon: 'Mi' },
    deepseek: { name: 'DeepSeek', color: '#5b6ee1', icon: 'D' },
};

/**
 * Task categories the router can classify queries into.
 */
export const TASK_TYPES = {
    CODE_GENERATION: 'code_generation',
    CODE_DEBUG: 'code_debug',
    CREATIVE_WRITING: 'creative_writing',
    ANALYSIS: 'analysis',
    MATH_REASONING: 'math_reasoning',
    SUMMARIZATION: 'summarization',
    TRANSLATION: 'translation',
    CONVERSATION: 'conversation',
    FACTUAL_QA: 'factual_qa',
    SYSTEM_DESIGN: 'system_design',
    DATA_EXTRACTION: 'data_extraction',
    INSTRUCTION_FOLLOWING: 'instruction_following',
};

/**
 * Each model has:
 * - id: unique identifier
 * - name: display name
 * - provider: key into PROVIDERS
 * - tier: 'frontier' | 'mid' | 'fast' | 'economy'
 * - contextWindow: max tokens
 * - costPer1kInput / costPer1kOutput: USD pricing
 * - latencyMs: typical first-token latency
 * - tokensPerSecond: output generation speed
 * - strengths: task types where this model excels (0-1 score)
 * - complexityRange: [min, max] complexity this model handles well (0-1 scale)
 * - qualityScore: overall quality rating (0-1)
 */
export const MODELS = [
    {
        id: 'gpt-4o',
        name: 'GPT-4o',
        provider: 'openai',
        tier: 'frontier',
        contextWindow: 128000,
        costPer1kInput: 0.0025,
        costPer1kOutput: 0.01,
        latencyMs: 400,
        tokensPerSecond: 90,
        qualityScore: 0.93,
        complexityRange: [0.3, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.93,
            [TASK_TYPES.CODE_DEBUG]: 0.91,
            [TASK_TYPES.CREATIVE_WRITING]: 0.88,
            [TASK_TYPES.ANALYSIS]: 0.92,
            [TASK_TYPES.MATH_REASONING]: 0.89,
            [TASK_TYPES.SUMMARIZATION]: 0.90,
            [TASK_TYPES.TRANSLATION]: 0.90,
            [TASK_TYPES.CONVERSATION]: 0.91,
            [TASK_TYPES.FACTUAL_QA]: 0.90,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.90,
            [TASK_TYPES.DATA_EXTRACTION]: 0.89,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.92,
        },
    },
    {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        provider: 'openai',
        tier: 'fast',
        contextWindow: 128000,
        costPer1kInput: 0.00015,
        costPer1kOutput: 0.0006,
        latencyMs: 250,
        tokensPerSecond: 120,
        qualityScore: 0.82,
        complexityRange: [0.0, 0.65],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.80,
            [TASK_TYPES.CODE_DEBUG]: 0.76,
            [TASK_TYPES.CREATIVE_WRITING]: 0.78,
            [TASK_TYPES.ANALYSIS]: 0.75,
            [TASK_TYPES.MATH_REASONING]: 0.72,
            [TASK_TYPES.SUMMARIZATION]: 0.82,
            [TASK_TYPES.TRANSLATION]: 0.80,
            [TASK_TYPES.CONVERSATION]: 0.84,
            [TASK_TYPES.FACTUAL_QA]: 0.82,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.68,
            [TASK_TYPES.DATA_EXTRACTION]: 0.83,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.81,
        },
    },
    {
        id: 'o3-mini',
        name: 'o3-mini',
        provider: 'openai',
        tier: 'mid',
        contextWindow: 128000,
        costPer1kInput: 0.0011,
        costPer1kOutput: 0.0044,
        latencyMs: 1500,
        tokensPerSecond: 60,
        qualityScore: 0.91,
        complexityRange: [0.5, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.92,
            [TASK_TYPES.CODE_DEBUG]: 0.90,
            [TASK_TYPES.CREATIVE_WRITING]: 0.72,
            [TASK_TYPES.ANALYSIS]: 0.88,
            [TASK_TYPES.MATH_REASONING]: 0.96,
            [TASK_TYPES.SUMMARIZATION]: 0.78,
            [TASK_TYPES.TRANSLATION]: 0.75,
            [TASK_TYPES.CONVERSATION]: 0.70,
            [TASK_TYPES.FACTUAL_QA]: 0.82,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.89,
            [TASK_TYPES.DATA_EXTRACTION]: 0.80,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.85,
        },
    },
    {
        id: 'claude-sonnet-4',
        name: 'Claude Sonnet 4',
        provider: 'anthropic',
        tier: 'frontier',
        contextWindow: 200000,
        costPer1kInput: 0.003,
        costPer1kOutput: 0.015,
        latencyMs: 450,
        tokensPerSecond: 80,
        qualityScore: 0.94,
        complexityRange: [0.3, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.95,
            [TASK_TYPES.CODE_DEBUG]: 0.94,
            [TASK_TYPES.CREATIVE_WRITING]: 0.92,
            [TASK_TYPES.ANALYSIS]: 0.95,
            [TASK_TYPES.MATH_REASONING]: 0.90,
            [TASK_TYPES.SUMMARIZATION]: 0.93,
            [TASK_TYPES.TRANSLATION]: 0.88,
            [TASK_TYPES.CONVERSATION]: 0.93,
            [TASK_TYPES.FACTUAL_QA]: 0.91,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.94,
            [TASK_TYPES.DATA_EXTRACTION]: 0.90,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.95,
        },
    },
    {
        id: 'claude-haiku-3.5',
        name: 'Claude Haiku 3.5',
        provider: 'anthropic',
        tier: 'fast',
        contextWindow: 200000,
        costPer1kInput: 0.0008,
        costPer1kOutput: 0.004,
        latencyMs: 200,
        tokensPerSecond: 130,
        qualityScore: 0.84,
        complexityRange: [0.0, 0.6],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.82,
            [TASK_TYPES.CODE_DEBUG]: 0.78,
            [TASK_TYPES.CREATIVE_WRITING]: 0.76,
            [TASK_TYPES.ANALYSIS]: 0.79,
            [TASK_TYPES.MATH_REASONING]: 0.74,
            [TASK_TYPES.SUMMARIZATION]: 0.84,
            [TASK_TYPES.TRANSLATION]: 0.82,
            [TASK_TYPES.CONVERSATION]: 0.85,
            [TASK_TYPES.FACTUAL_QA]: 0.83,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.70,
            [TASK_TYPES.DATA_EXTRACTION]: 0.85,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.83,
        },
    },
    {
        id: 'claude-opus-4',
        name: 'Claude Opus 4',
        provider: 'anthropic',
        tier: 'frontier',
        contextWindow: 200000,
        costPer1kInput: 0.015,
        costPer1kOutput: 0.075,
        latencyMs: 800,
        tokensPerSecond: 50,
        qualityScore: 0.97,
        complexityRange: [0.6, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.96,
            [TASK_TYPES.CODE_DEBUG]: 0.95,
            [TASK_TYPES.CREATIVE_WRITING]: 0.97,
            [TASK_TYPES.ANALYSIS]: 0.97,
            [TASK_TYPES.MATH_REASONING]: 0.94,
            [TASK_TYPES.SUMMARIZATION]: 0.94,
            [TASK_TYPES.TRANSLATION]: 0.91,
            [TASK_TYPES.CONVERSATION]: 0.95,
            [TASK_TYPES.FACTUAL_QA]: 0.93,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.97,
            [TASK_TYPES.DATA_EXTRACTION]: 0.92,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.96,
        },
    },
    {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        provider: 'google',
        tier: 'fast',
        contextWindow: 1000000,
        costPer1kInput: 0.0001,
        costPer1kOutput: 0.0004,
        latencyMs: 180,
        tokensPerSecond: 150,
        qualityScore: 0.83,
        complexityRange: [0.0, 0.65],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.81,
            [TASK_TYPES.CODE_DEBUG]: 0.78,
            [TASK_TYPES.CREATIVE_WRITING]: 0.76,
            [TASK_TYPES.ANALYSIS]: 0.80,
            [TASK_TYPES.MATH_REASONING]: 0.79,
            [TASK_TYPES.SUMMARIZATION]: 0.84,
            [TASK_TYPES.TRANSLATION]: 0.83,
            [TASK_TYPES.CONVERSATION]: 0.82,
            [TASK_TYPES.FACTUAL_QA]: 0.84,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.72,
            [TASK_TYPES.DATA_EXTRACTION]: 0.85,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.80,
        },
    },
    {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        provider: 'google',
        tier: 'frontier',
        contextWindow: 1000000,
        costPer1kInput: 0.00125,
        costPer1kOutput: 0.01,
        latencyMs: 500,
        tokensPerSecond: 75,
        qualityScore: 0.93,
        complexityRange: [0.3, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.93,
            [TASK_TYPES.CODE_DEBUG]: 0.90,
            [TASK_TYPES.CREATIVE_WRITING]: 0.85,
            [TASK_TYPES.ANALYSIS]: 0.92,
            [TASK_TYPES.MATH_REASONING]: 0.94,
            [TASK_TYPES.SUMMARIZATION]: 0.91,
            [TASK_TYPES.TRANSLATION]: 0.89,
            [TASK_TYPES.CONVERSATION]: 0.88,
            [TASK_TYPES.FACTUAL_QA]: 0.91,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.91,
            [TASK_TYPES.DATA_EXTRACTION]: 0.90,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.90,
        },
    },
    {
        id: 'llama-3.3-70b',
        name: 'Llama 3.3 70B',
        provider: 'meta',
        tier: 'mid',
        contextWindow: 128000,
        costPer1kInput: 0.00018,
        costPer1kOutput: 0.00018,
        latencyMs: 300,
        tokensPerSecond: 100,
        qualityScore: 0.85,
        complexityRange: [0.1, 0.75],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.84,
            [TASK_TYPES.CODE_DEBUG]: 0.80,
            [TASK_TYPES.CREATIVE_WRITING]: 0.79,
            [TASK_TYPES.ANALYSIS]: 0.82,
            [TASK_TYPES.MATH_REASONING]: 0.78,
            [TASK_TYPES.SUMMARIZATION]: 0.83,
            [TASK_TYPES.TRANSLATION]: 0.80,
            [TASK_TYPES.CONVERSATION]: 0.84,
            [TASK_TYPES.FACTUAL_QA]: 0.83,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.76,
            [TASK_TYPES.DATA_EXTRACTION]: 0.82,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.82,
        },
    },
    {
        id: 'mistral-large',
        name: 'Mistral Large',
        provider: 'mistral',
        tier: 'mid',
        contextWindow: 128000,
        costPer1kInput: 0.002,
        costPer1kOutput: 0.006,
        latencyMs: 350,
        tokensPerSecond: 85,
        qualityScore: 0.88,
        complexityRange: [0.2, 0.85],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.88,
            [TASK_TYPES.CODE_DEBUG]: 0.85,
            [TASK_TYPES.CREATIVE_WRITING]: 0.83,
            [TASK_TYPES.ANALYSIS]: 0.86,
            [TASK_TYPES.MATH_REASONING]: 0.84,
            [TASK_TYPES.SUMMARIZATION]: 0.86,
            [TASK_TYPES.TRANSLATION]: 0.90,
            [TASK_TYPES.CONVERSATION]: 0.85,
            [TASK_TYPES.FACTUAL_QA]: 0.85,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.82,
            [TASK_TYPES.DATA_EXTRACTION]: 0.85,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.86,
        },
    },
    {
        id: 'deepseek-r1',
        name: 'DeepSeek R1',
        provider: 'deepseek',
        tier: 'mid',
        contextWindow: 128000,
        costPer1kInput: 0.00055,
        costPer1kOutput: 0.0022,
        latencyMs: 1200,
        tokensPerSecond: 55,
        qualityScore: 0.90,
        complexityRange: [0.4, 1.0],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.91,
            [TASK_TYPES.CODE_DEBUG]: 0.88,
            [TASK_TYPES.CREATIVE_WRITING]: 0.70,
            [TASK_TYPES.ANALYSIS]: 0.86,
            [TASK_TYPES.MATH_REASONING]: 0.95,
            [TASK_TYPES.SUMMARIZATION]: 0.78,
            [TASK_TYPES.TRANSLATION]: 0.74,
            [TASK_TYPES.CONVERSATION]: 0.68,
            [TASK_TYPES.FACTUAL_QA]: 0.80,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.85,
            [TASK_TYPES.DATA_EXTRACTION]: 0.78,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.82,
        },
    },
    {
        id: 'deepseek-v3',
        name: 'DeepSeek V3',
        provider: 'deepseek',
        tier: 'mid',
        contextWindow: 128000,
        costPer1kInput: 0.00027,
        costPer1kOutput: 0.0011,
        latencyMs: 350,
        tokensPerSecond: 90,
        qualityScore: 0.87,
        complexityRange: [0.1, 0.8],
        strengths: {
            [TASK_TYPES.CODE_GENERATION]: 0.88,
            [TASK_TYPES.CODE_DEBUG]: 0.85,
            [TASK_TYPES.CREATIVE_WRITING]: 0.78,
            [TASK_TYPES.ANALYSIS]: 0.84,
            [TASK_TYPES.MATH_REASONING]: 0.86,
            [TASK_TYPES.SUMMARIZATION]: 0.83,
            [TASK_TYPES.TRANSLATION]: 0.80,
            [TASK_TYPES.CONVERSATION]: 0.82,
            [TASK_TYPES.FACTUAL_QA]: 0.84,
            [TASK_TYPES.SYSTEM_DESIGN]: 0.80,
            [TASK_TYPES.DATA_EXTRACTION]: 0.83,
            [TASK_TYPES.INSTRUCTION_FOLLOWING]: 0.84,
        },
    },
];

export function getModel(id) {
    return MODELS.find(m => m.id === id);
}

export function getProvider(model) {
    return PROVIDERS[model.provider];
}
